/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SecurityEventsRouteImport } from './routes/security-events'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityEventsRoute = SecurityEventsRouteImport.update({
  id: '/security-events',
  path: '/security-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/models': typeof ModelsRoute
  '/overview': typeof OverviewRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/security-events': typeof SecurityEventsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/models': typeof ModelsRoute
  '/overview': typeof OverviewRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/security-events': typeof SecurityEventsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/models': typeof ModelsRoute
  '/overview': typeof OverviewRoute
  '/playground': typeof PlaygroundRoute
  '/policies': typeof PoliciesRoute
  '/security-events': typeof SecurityEventsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit-logs'
    | '/models'
    | '/overview'
    | '/playground'
    | '/policies'
    | '/security-events'
    | '/settings'
    | '/system-health'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit-logs'
    | '/models'
    | '/overview'
    | '/playground'
    | '/policies'
    | '/security-events'
    | '/settings'
    | '/system-health'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit-logs'
    | '/models'
    | '/overview'
    | '/playground'
    | '/policies'
    | '/security-events'
    | '/settings'
    | '/system-health'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  ModelsRoute: typeof ModelsRoute
  OverviewRoute: typeof OverviewRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PoliciesRoute: typeof PoliciesRoute
  SecurityEventsRoute: typeof SecurityEventsRoute
  SettingsRoute: typeof SettingsRoute
  SystemHealthRoute: typeof SystemHealthRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-events': {
      id: '/security-events'
      path: '/security-events'
      fullPath: '/security-events'
      preLoaderRoute: typeof SecurityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditLogsRoute: AuditLogsRoute,
  ModelsRoute: ModelsRoute,
  OverviewRoute: OverviewRoute,
  PlaygroundRoute: PlaygroundRoute,
  PoliciesRoute: PoliciesRoute,
  SecurityEventsRoute: SecurityEventsRoute,
  SettingsRoute: SettingsRoute,
  SystemHealthRoute: SystemHealthRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
